### ISSUE TITLE
Seems to conflict with Socket.IO in debug mode

### ISSUE THREAD

**Issue by Dreen** [rynti/node-shutdown-handler#1]
When running in debug mode I get the following message:

```
< /home/dreen/RealDash/node_modules/shutdown-handler/shutdown-handler.js:40
< process.stdin.setRawMode(true);
<        ^
< TypeError: Object #<Socket> has no method 'setRawMode'
<     at Object.<anonymous> (/home/dreen/RealDash/node_modules/shutdown-handler/shutdown-handler.js:40:15)
<     at Module._compile (module.js:456:26)
<     at Object.Module._extensions..js (module.js:474:10)
<     at Module.load (module.js:356:32)
<     at Function.Module._load (module.js:312:12)
<     at Module.require (module.js:364:17)
<     at require (module.js:380:17)
<     at Object.<anonymous> (/home/dreen/RealDash/server/main.js:5:12)
<     at Module._compile (module.js:456:26)
<     at Object.Module._extensions..js (module.js:474:10)
program terminated
```

I am guessing there is a conflict with Socket.IO since I am using that too.

**Comment by rynti** [comment]
Should be fixed with #2.
